name: main 

on:
  workflow_dispatch:  # Permite apenas a execução manual pela aba Actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Restaurar hxh.json a partir do segredo
        run: |
          echo "$GCP_JSON_BASE64" | base64 -d > hxh.json
        shell: bash
        env:
          GCP_JSON_BASE64: ${{ secrets.GCP_JSON_BASE64 }}

      - name: Instalar dependências e navegadores
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps

      - name: Executar o script
        env:
          TZ: "America/Sao_Paulo" # Garante o horário de Brasília
        run: python main.py

      - name: Salvar Screenshots de Debug
        uses: actions/upload-artifact@v4
        if: always() # Garante que o GitHub salve as fotos mesmo se o Python "crashar"
        with:
          name: screenshots-shopee
          path: /tmp/debug/
